language: r
pandoc_version: 1.19.2.1
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
env:
  global:
    secure: cHwK3R2wtd/JcdbO28X8BQEwAlE1JN6CSpJZcSh0twqFbmGcyoamuBrM5xM+jHl6v9sMx89RjmdyALyR1iPs6m3xx94CXtaw36fqYHGDM8haKv4vTkG6sTKYAWN2s5bk13Mq5NUpUWKBd2VWYu6sJ+nEn975FNetNmhcxz/RwpZoDqbaC9fyBLpk+PhyRIl5kWuJR125DfECBgGNXgPR3pLzIRBKFgcCXvECUPo/qYPJ402Spfd2IImXt5ugE1FXY2Fp7JL1buTLCNk5amPsjMubWUF/JD+JQk5T+VP1sUUXjTmLeLdastCX+Q2BezMRDvMCUGoC3fjc5m/76+v9kodoyGu+h5kFuSaWBeVZEGwha5KZJUk/d5/1EFkTsFgt+N7+xF8txhQX7PbWnnpVj5VizPaz0zEqAvqUrnaUxLadTcWRgv1R03Qol5NWBE0UUuRlAeDQVZtZR7ZXaXjxY2PVeHfG4IyeQh4jxr0njqYpWeWpEZ/53fkeB8kZhQ4biI1zlsdMEkO97aDU9wwBuvJBcJYoBPcIFgUTMuPdGprm76FK79LTMLmr4lWp8b3MhqUIV80DVRDo0wOChUwJH8+60PovEvKHcOS3rjz+uiL+x2HCrZbNVcm2ljHVZovRzqI76/r4aUjHpFxLZI1iPENVrjB32JsNenkbFXPohUI=
